/**
 * AI Insight Card Component
 *
 * Displays insights generated by Claude's AI analysis.
 * Supports the expanded evidence layer for detail panels.
 */

import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Sparkles,
  ChevronRight,
  ChevronDown,
  AlertCircle,
  Clock,
  Info,
  CheckCircle2,
  Brain,
  Lightbulb,
  AlertTriangle,
} from 'lucide-react';
import { AIInsight, ActionItem, ReasoningChain } from '../../services/synthesis/aiAnalysis';

interface AIInsightCardProps {
  insight: AIInsight;
  variant?: 'lead' | 'secondary';
  onClick?: () => void;
}

const urgencyConfig = {
  today: {
    label: 'Do this today',
    className: 'urgency-today',
    icon: AlertCircle,
  },
  week: {
    label: 'This week',
    className: 'urgency-week',
    icon: Clock,
  },
  knowing: {
    label: 'Worth knowing',
    className: 'urgency-knowing',
    icon: Info,
  },
};

const confidenceLabels = {
  high: 'High confidence',
  moderate: 'Moderate confidence',
  low: 'Low confidence',
};

const priorityColors = {
  critical: 'text-red-400',
  recommended: 'text-amber-400',
  optional: 'text-olive-muted',
};

export const AIInsightCard: React.FC<AIInsightCardProps> = ({
  insight,
  variant = 'secondary',
  onClick,
}) => {
  const [showDetails, setShowDetails] = useState(false);
  const [showReasoning, setShowReasoning] = useState(false);
  const urgency = urgencyConfig[insight.urgency];
  const UrgencyIcon = urgency.icon;

  const isLead = variant === 'lead';

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className={`
        ${isLead ? 'lead-card' : 'secondary-card'}
        p-5 cursor-pointer group relative
        ${isLead ? 'border-l-4 border-amber-500' : ''}
      `}
      onClick={onClick}
      whileHover={{ scale: 1.005 }}
      transition={{ type: 'spring', stiffness: 400, damping: 30 }}
    >
      {/* AI Badge */}
      <div className="absolute top-3 right-3 flex items-center gap-1.5 text-xs text-olive-muted">
        <Sparkles className="w-3 h-3 text-amber-500/60" />
        <span className="opacity-60">AI Analysis</span>
      </div>

      {/* Urgency Pill + Confidence */}
      <div className="flex items-center gap-3 mb-3">
        <span className={`urgency-pill ${urgency.className} inline-flex items-center gap-1.5`}>
          <UrgencyIcon className="w-3 h-3" />
          {urgency.label}
        </span>
        {insight.confidence && (
          <span className="text-xs text-olive-muted">
            {confidenceLabels[insight.confidence]}
          </span>
        )}
      </div>

      {/* Headline */}
      <h3 className={`
        font-display font-semibold text-olive-primary mb-2
        ${isLead ? 'text-display-lead' : 'text-lg'}
      `}>
        {insight.headline}
      </h3>

      {/* Data Point (key metric) */}
      {insight.dataPoint && (
        <div className="text-sm text-amber-400/80 font-mono mb-2">
          {insight.dataPoint}
        </div>
      )}

      {/* Body */}
      <p className="text-body-card text-olive-secondary leading-relaxed mb-4">
        {insight.body}
      </p>

      {/* Action Items */}
      {insight.actionItems && insight.actionItems.length > 0 && (
        <div className="space-y-2 mb-4">
          <div className="flex items-center gap-2 text-xs text-olive-muted uppercase tracking-wider">
            <CheckCircle2 className="w-3.5 h-3.5" />
            Action Items
          </div>
          <ul className="space-y-2">
            {insight.actionItems.map((action, i) => (
              <ActionItemRow key={i} action={action} />
            ))}
          </ul>
        </div>
      )}

      {/* Peripheral Impacts (expandable) */}
      {insight.peripheralImpacts && insight.peripheralImpacts.length > 0 && (
        <div className="border-t border-olive pt-3 mt-3">
          <button
            onClick={(e) => {
              e.stopPropagation();
              setShowDetails(!showDetails);
            }}
            className="flex items-center gap-2 text-xs text-olive-muted hover:text-olive-secondary transition-colors w-full"
          >
            <Brain className="w-3.5 h-3.5" />
            <span className="uppercase tracking-wider">Peripheral Impacts</span>
            <ChevronDown
              className={`w-4 h-4 ml-auto transition-transform ${
                showDetails ? 'rotate-180' : ''
              }`}
            />
          </button>

          <AnimatePresence>
            {showDetails && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="overflow-hidden"
              >
                <div className="pt-3 space-y-2">
                  {insight.peripheralImpacts.map((impact, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-2 text-sm text-olive-secondary"
                    >
                      <div className="w-1.5 h-1.5 rounded-full bg-amber-500/50" />
                      <span>{impact}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* Reasoning Chain (expandable) */}
      {insight.reasoning && (
        <div className="border-t border-olive pt-3 mt-3">
          <button
            onClick={(e) => {
              e.stopPropagation();
              setShowReasoning(!showReasoning);
            }}
            className="flex items-center gap-2 text-xs text-olive-muted hover:text-olive-secondary transition-colors w-full"
          >
            <Lightbulb className="w-3.5 h-3.5" />
            <span className="uppercase tracking-wider">How We Got Here</span>
            <ChevronDown
              className={`w-4 h-4 ml-auto transition-transform ${
                showReasoning ? 'rotate-180' : ''
              }`}
            />
          </button>

          <AnimatePresence>
            {showReasoning && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="overflow-hidden"
              >
                <ReasoningSection reasoning={insight.reasoning} />
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      )}

      {/* Confidence Reason */}
      {insight.confidenceReason && (
        <div className="mt-3 text-xs text-olive-muted italic">
          {insight.confidenceReason}
        </div>
      )}

      {/* Domain Tags */}
      {insight.domains && insight.domains.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mt-4">
          {insight.domains.map((domain) => (
            <span
              key={domain}
              className="px-2 py-0.5 text-xs rounded-full bg-white/5 text-olive-muted"
            >
              {domain.replace('_', ' ')}
            </span>
          ))}
        </div>
      )}
    </motion.div>
  );
};

/**
 * Action Item Row - shows task with effort and priority
 */
const ActionItemRow: React.FC<{ action: ActionItem }> = ({ action }) => {
  return (
    <li className="flex items-start gap-2 text-sm text-olive-secondary">
      <ChevronRight className={`w-4 h-4 shrink-0 mt-0.5 ${priorityColors[action.priority]}`} />
      <div className="flex-1">
        <span>{action.task}</span>
        <div className="flex items-center gap-2 mt-0.5 text-xs text-olive-muted">
          <span>{action.timeEstimate}</span>
          <span className="opacity-50">•</span>
          <span className={priorityColors[action.priority]}>{action.priority}</span>
        </div>
        {action.why && (
          <p className="text-xs text-olive-muted mt-0.5">{action.why}</p>
        )}
      </div>
    </li>
  );
};

/**
 * Reasoning Section - shows the full reasoning chain
 */
const ReasoningSection: React.FC<{ reasoning: ReasoningChain }> = ({ reasoning }) => {
  return (
    <div className="pt-3 space-y-3 text-sm">
      {/* Observation → Interpretation → Implication → Recommendation */}
      <div className="space-y-2">
        <div>
          <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">Observation</div>
          <p className="text-olive-secondary">{reasoning.observation}</p>
        </div>
        <div>
          <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">Interpretation</div>
          <p className="text-olive-secondary">{reasoning.interpretation}</p>
        </div>
        <div>
          <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">Family Impact</div>
          <p className="text-olive-secondary">{reasoning.familyImplication}</p>
        </div>
        <div>
          <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">Recommendation</div>
          <p className="text-olive-secondary">{reasoning.recommendation}</p>
        </div>
      </div>

      {/* Assumptions */}
      {reasoning.assumptions && reasoning.assumptions.length > 0 && (
        <div className="p-2 rounded bg-white/[0.02]">
          <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">Assumptions</div>
          <ul className="space-y-1">
            {reasoning.assumptions.map((assumption, i) => (
              <li key={i} className="text-xs text-olive-muted flex items-start gap-1.5">
                <span className="opacity-50">•</span>
                {assumption}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Counterpoints */}
      {reasoning.counterpoints && reasoning.counterpoints.length > 0 && (
        <div className="p-2 rounded bg-white/[0.02]">
          <div className="flex items-center gap-1.5 text-xs text-olive-muted uppercase tracking-wider mb-1">
            <AlertTriangle className="w-3 h-3" />
            What Could Change This
          </div>
          <ul className="space-y-1">
            {reasoning.counterpoints.map((point, i) => (
              <li key={i} className="text-xs text-olive-muted flex items-start gap-1.5">
                <span className="opacity-50">•</span>
                {point}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
};

/**
 * AI Analysis Summary Card
 * Shows the overall assessment and hidden connections
 */
interface AIAnalysisSummaryProps {
  overallAssessment: string;
  hiddenConnections: string[];
  familyFocusedSummary: string;
  phaseRelevance?: string;
}

export const AIAnalysisSummary: React.FC<AIAnalysisSummaryProps> = ({
  overallAssessment,
  hiddenConnections,
  familyFocusedSummary,
  phaseRelevance,
}) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="secondary-card p-4"
    >
      <div className="flex items-start gap-3">
        <div className="p-2 rounded-lg bg-amber-500/10">
          <Sparkles className="w-4 h-4 text-amber-500" />
        </div>
        <div className="flex-1 min-w-0">
          <h4 className="text-sm font-medium text-olive-primary mb-1">
            AI Analysis
          </h4>
          <p className="text-sm text-olive-secondary leading-relaxed">
            {overallAssessment}
          </p>

          {(hiddenConnections.length > 0 || familyFocusedSummary || phaseRelevance) && (
            <button
              onClick={() => setExpanded(!expanded)}
              className="text-xs text-amber-500/70 hover:text-amber-500 mt-2 flex items-center gap-1"
            >
              {expanded ? 'Show less' : 'See hidden connections'}
              <ChevronDown
                className={`w-3 h-3 transition-transform ${
                  expanded ? 'rotate-180' : ''
                }`}
              />
            </button>
          )}

          <AnimatePresence>
            {expanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                className="overflow-hidden"
              >
                {hiddenConnections.length > 0 && (
                  <div className="mt-3 space-y-2">
                    <div className="text-xs text-olive-muted uppercase tracking-wider">
                      Hidden Connections
                    </div>
                    {hiddenConnections.map((connection, i) => (
                      <p
                        key={i}
                        className="text-sm text-olive-secondary pl-3 border-l-2 border-amber-500/30"
                      >
                        {connection}
                      </p>
                    ))}
                  </div>
                )}

                {familyFocusedSummary && (
                  <div className="mt-3 p-3 rounded-lg bg-white/[0.02]">
                    <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">
                      Family Impact
                    </div>
                    <p className="text-sm text-olive-secondary">
                      {familyFocusedSummary}
                    </p>
                  </div>
                )}

                {phaseRelevance && (
                  <div className="mt-3 p-3 rounded-lg bg-white/[0.02]">
                    <div className="text-xs text-olive-muted uppercase tracking-wider mb-1">
                      Phase Relevance
                    </div>
                    <p className="text-sm text-olive-secondary">
                      {phaseRelevance}
                    </p>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.div>
  );
};
